### ISSUE TITLE
telegram as the operator's own channel

### ISSUE THREAD

**Issue by jakceo** [LiveHelperChat/telegram#13]
Is it possible to use the telegram as the operator's own channel? would be useful to provide emergency support in cases out of hours when the operator was not on the computer. Does the LHC have anything that might work like this?

**Comment by remdex** [comment]
Hi,
Yes you can use that way extension also. Create a bot. And later make it as support client. So you will receive notifications from telegram bot and be able to chat directly with customer using telegram.
