### ISSUE TITLE
Problem with email contains underline "_"

### ISSUE THREAD

**Issue by Dansk00** [LiveHelperChat/telegram#14]
when the user put some email with "_", telegram dont receive the notification :(

**Comment by remdex** [comment]
Can you type message example?

**Comment by Dansk00** [comment]
Sure, eg:

Client enter in my page chat 

Tecnologiadc.com.br/chat

Fill the form

Name

email (the problem is here, when the e-mail has underline example_test@emailtest.com, i dont received the telegram notification, but when email dont have underline  eg exampletest@emailtest.com Works perfect.)

Enterprise 
Message

**Comment by remdex** [comment]
So you are using telegram as client? I mean. Once visitor starts a chat, you get a message with chat data? E-mail is put in message or E-mail field?

**Comment by remdex** [comment]
Sorry, but i tried and can't duplicate...

**Comment by Dansk00** [comment]
But you try in your inviroment ?

**Comment by remdex** [comment]
Yes. Contact me on skype and I give you url to test will see if i receive notification. My skype nick remdex

**Comment by Dansk00** [comment]
Ok, i will

**Comment by Dansk00** [comment]
Hi, im back, i saw my problem...

Its because i want to receive the notification with the variable of email... So  i to

Lhc_web > extension > Bootstrap  and in bootstrap.php
Line 441

I add the string e-mail

But, when i add , emails with underline doest work... So, the extension Works Fine If you dont want do received the notify with email
