### ISSUE TITLE
Support for Long Pooling

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/telegram#15]
Hi, 
I try to use it Test server, before uploading to production, but access from outside is closed. Because of this, i think, I receive error: 

"Telegram returned an invalid response! Please review your bot name and API key."

**Comment by remdex** [comment]
Not sure how i'm suppose to help you. Make sure you are using HTTPS on your demo server. Telegram to issue callbacks requres lhc to be installed on HTTPS.

**Comment by Vintic** [comment]
I mean, to use Long Pooling Hook, not WebHook. This hook, do not need a server with a domain name, it will send getUpdates() request to api.Telegam, to receive modifications, like new messages
