### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/telegram#16]
Posibility to upload and set self signed certificate:

`$result = $telegram->setWebhook($hook_url, ['certificate' => '/path/to/certificate']);`

And can you please specify, what token should lock like?
starts with prefix "bot" + "token"  =  "bot11111:123456789" or like = "11111:123456789"?
AND Bot username should be exact as in telergam? with '@'  =  @ABC_Bot
or not, like  =  ABC_Bot.

I ask because I receive an error: 
`Telegram returned an invalid response! Please review your bot name and API key. `

**Comment by Vintic** [comment]
Ok I set webHook manually, by http request,

Now when i send message from telegram to BOT, -> appears new chat message on LHC page,
that's ok. But when I try to response, message do not appear in telegram, and in LHC "System assistant" return message "null".

**Comment by Vintic** [comment]
OK, I found the solution: https://github.com/guzzle/guzzle/issues/394

In ...\extension\lhctelegram\vendor\longman\telegram-bot\src 
Replace:
`self::setClient(new Client(['base_uri' => self::$api_base_uri]));`
with:
`self::setClient(new Client(['base_uri' => self::$api_base_uri, 'verify' => false]));`
Thanks.

**Comment by tom10271** [comment]
`'verify' => false` is a bad solution. It definitely works as you disarmed the checking

**Comment by dkwiebe** [comment]
@Vintic Letsencrypt makes it easy and fairly simple to get your own certificates.   That would save disabling verification.
