### ISSUE TITLE
Telegram bot stopped to work from like 1-2 month

### ISSUE THREAD

**Issue by xion87** [LiveHelperChat/telegram#20]
I noticed telegram bot stopped to work (i think telegram have updated their api) any solution for work it again?

**Comment by remdex** [comment]
Hi,
I'll test during the weekend does it really stopped working as :) Just what exactly stopped you don't receive message from bot or what workflow does not work for you anymore?

**Comment by xion87** [comment]
at start the bot was receiving only few notification of chat request, but when trying to accept them was doing doing, then i tried to upgrade livehelperchat and now stopped to work completly, no bot reaction and it dont reply to any command and message

**Comment by remdex** [comment]
Ok, so i can confirm that on my end everything bot. I can chat with customer form telegram. Means it's something else you are missing...

**Comment by xion87** [comment]
i tried to do a fresh install (it have fixed some issue with livehelperchat home page), installed a fresh bot and put the codes but the bot is still not work or reacting, i have to use the @ on bot name? also the api come with  2 number group separated by : , where i am wrong?

**Comment by remdex** [comment]
1. You do not have to use @ in bot name.
2. I can't help much there as all works here, without looking personally in your issue. If you need help contact by Skype. But skype support is paid as all works here.

**Comment by xion87** [comment]
I just discovered was cloduflare blocking the ip 91.108.6.90 (telegram ip) is that why was never worked... pretty fun fact....

**Comment by remdex** [comment]
That's why it's impossible to know all the problems then someone writes it does not work for me :D
