### ISSUE TITLE
Chat notification

### ISSUE THREAD

**Issue by alxzhdanov** [LiveHelperChat/telegram#21]
Hello. 
At first, thank you, for this extension. 
I create following steps on my site with lhc:
1. visitor open web site.  Visit 3 pages. 
2. Bot open dialog and ask question. If answer was standart - bot reply. 
3. After first 3 questions chat transfered to operator.

Problem: i get notification in telegram when visitor open first page, before dialog with bot starts. For each visitor. But when chat transfered to operator I haven't any notification.

**Comment by remdex** [comment]
Hi,

I do not think at the moment workflows including bot and bot transfering chats to pending states is supported yet.

**Comment by remdex** [comment]
Hi,
Implemented these changes. Please update to version from github and lhc has to be 3.36v min.
