### ISSUE TITLE
Pictures and another attached files

### ISSUE THREAD

**Issue by Nucleardragon88** [LiveHelperChat/telegram#24]
Operator can send picture by the Telegram client via bot and website widget can show this picture to visitor, but if visitor will send photo or any another type of file  to operator in Telegram client we can't see the picture or any files, only file ID.

**Comment by remdex** [comment]
Yes, this one need enhancement :)

**Comment by remdex** [comment]
Implemented fix. But you will have to update to the most Recent Version.
