### ISSUE TITLE
Option "Email when chat is closed automatically" sends email when closed from telegram.

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/telegram#27]
When option "Inform then chat is closed automatically, only mail notification is send." is checked, and chat is closed from telegram email will be sent.
And when "Inform then chat is closed by operator, only mail notification is send." is checked, email wont be sent, when closed from telegram.

**Comment by remdex** [comment]
How exactly you closed the chat? because in the code /endchat it's identical code to web action. So sounds suspicious..

**Comment by Vintic** [comment]
yes , I use /endchat

**Comment by remdex** [comment]
I closed chat from telegram with /endchat and got mail notification. In department was checked only

" Inform then chat is closed by operator, only mail notification is send."

**Comment by remdex** [comment]
Update this file. It was sending e-mail only if all notifications were checked.
https://github.com/LiveHelperChat/livehelperchat/commit/c29e9c920c84af3a2cb29d1f1adbd424d4635d27
