### ISSUE TITLE
Can I Let LiveHelperChat using the webhook on different server?

### ISSUE THREAD

**Issue by haizad** [LiveHelperChat/telegram#28]
Hi,

I got error of (Webhook was not set! Error: 400 Bad Request: bad webhook: HTTPS url must be provided for webhook) when I try to set webhook as I am currently hosting livehelperchat on server that only serve HTTP. I try not to change the HTTP to HTTPS because of certain reason.

I have a different server which have HTTPS, let just call it https://myotherserver. So I thought by giving the same **bot API token** during 
(1) setup the telegram bot on liveHelperChat and ;
(2) setting through telegram API (
https://api.telegram.org/bot **bot API token** /setWebHook?url=https://myOtherServer/hook )

, liveHelperChat will just letting me using the same webhook url as a callback url if the bot token are similar. But it does not work that way. 

What I already did was call web request to;
https://api.telegram.org/botXXXXXXX/setWebHook?url=https://myOtherServer/hook

and manage to receive return the webhook URL by calling;
https://api.telegram.org/botXXXXXXX/getWebhookInfo

Please excuse my grammar.

![Screenshot from 2020-06-07 14-51-48](https://user-images.githubusercontent.com/23258127/83962266-ae58b580-a8ce-11ea-8695-8d0bf65b4324.png)
 

Thank you in advance.

**Comment by remdex** [comment]
Nothing will be changed in extension as https is a must
