### ISSUE TITLE
setwebhook giving 503 (Service Temporarily Unavailable)

### ISSUE THREAD

**Issue by azchishti** [LiveHelperChat/telegram#37]
After adding bot successfully when we try to add setwebhook, its giving 503 (Service Temporarily Unavailable). Any guide or help to mange this issue

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/debug/

And make sure you have installed dependencies via composer.

**Comment by azchishti** [comment]
after enabling getting following errors
`Error Object
(
    [message:protected] => Class 'Longman\TelegramBot\Telegram' not found
    [string:Error:private] => 
    [code:protected] => 0
    [file:protected] => /{website_path}/cache/compiledtemplates/ce73be756daecf8db7d367826bc7a7a1.php
    [line:protected] => 2
    [trace:Error:private] => Array
        (
            [0] => Array
                (
                    [file] => /{website_path}/lib/core/lhcore/lhmodule.php
                    [line] => 106
                    [function] => include
                )

            [1] => Array
                (
                    [file] => /{website_path}/lib/core/lhcore/lhmodule.php
                    [line] => 578
                    [function] => runModule
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

            [2] => Array
                (
                    [file] => /{server_path}/index.php
                    [line] => 50
                    [function] => moduleInit
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

        )

    [previous:Error:private] => 
)`

**Comment by remdex** [comment]
Read again my comment...
