### ISSUE TITLE
Webhook setup step failing

### ISSUE THREAD

**Issue by lexa500** [LiveHelperChat/telegram#39]
Hi currently I run livehelper chat in docker compose with nodejs (just as described on doc pages) I try to install telegram module, all is going smoth until last step with webhook. all I get is 
`"Webhook was not set! Error: 400 Bad Request: bad webhook: HTTPS url must be provided for webhook"`
error. 
docker is behind my nginx proxy with https.
I believe there is an issue with 
`<a title="http://myurlhere/telegram/callback/2" href="/site_admin/telegram/setwebhook/2" class="btn btn-xs btn-info">Set webhook</a>` block. Can you please provide any help here?

**Comment by remdex** [comment]
It has to be http(s) as ot writes.

**Comment by akuplensky-aparavi** [comment]
so, can you please share a bit of details?

**Comment by remdex** [comment]
If you don't know what is https, ssl certifikates that's really not scope of lhc. Just hire some web developer who has all the knowledge...

**Comment by akuplensky-aparavi** [comment]
well I know a bit of https and http (: 
The question was why  webhook tries to use http instead of https and gets 400 response and how can I fix this?

**Comment by remdex** [comment]
You have to setup lhc on https and use https webhook url.

**Comment by akuplensky-aparavi** [comment]
Ok, thanks for solution. But is there a way to set it somehow within my setup?
I have nginx proxy (facing internets, https) and it proxies to some inner machine with lhc in docker.
Seems that this inner docker uses somehow bundled nginx on 80/http. So I wonder if I can change smth in plugin to  run in https?

**Comment by remdex** [comment]
You should either
1. Setup https upfront of your lhc docker
2. Modify docker and setup ssl there.
All that up to you how you do that :)
