### ISSUE TITLE
Error for this extension due to lack of  * autoload.php * folder on vendor directory ....

### ISSUE THREAD

**Issue by tgd1973** [LiveHelperChat/telegram#40]
Hello! Something is missing from the folders structure ...
Running the cron with this command:
php cron.php -s site_admin -e lhctelegram -c cron/update_structure

i have the eeror below...

`
root@s1:/home/xxxx/web/xxxx/public_html# php cron.php -s site_admin -e lhctelegram -c cron/update_structure
Unexpected error, the message was : include_once(extension/lhctelegram/vendor/autoload.php): failed to open stream: No such file or directory in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12
PHP Warning:  include_once(extension/lhctelegram/vendor/autoload.php): failed to open stream: No such file or directory in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12

Warning: include_once(extension/lhctelegram/vendor/autoload.php): failed to open stream: No such file or directory in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12
Unexpected error, the message was : include_once(): Failed opening 'extension/lhctelegram/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12
PHP Warning:  include_once(): Failed opening 'extension/lhctelegram/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12

Warning: include_once(): Failed opening 'extension/lhctelegram/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/xxxx/web/xxxx/public_html/extension/lhctelegram/bootstrap/bootstrap.php on line 12
No queries to execute found

`

In the vendor folder there are no files like ' autoload.php ' to which the bootstrap.php file refers to line 12 in the error I presented above ...  Something got lost along the way

**Comment by tgd1973** [comment]
However I don't know if it's due to the autoload.php folder but when I go to click on the green/blue label from the Telegram backoffice
  bots "Callback URL" I get a error page:

We’ll be back soon!
This service is currently unavailable due to an emergency or scheduled maintenance window. The service will be back online within the next two hours. Sorry for the inconvenience.

— Online Service Support Team

**Comment by remdex** [comment]
Read install manual and install composer dependencies.

**Comment by tgd1973** [comment]
I followed the documentation of the : README.md  ...

## Install instructions

1. Clone github repository
2. Rename cloned folder of telegram to lhctelegram and put it in extension/ directory
3. Activate extension in main Live Helper Chat settings file `lhc_web/settings/settings.ini.php` file
``` 
'extensions' => 
    array (          
        'lhctelegram'
    ),
```
4. Install composer requirements with. You have to download composer or just have it installed already.
``` 
cd extension/lhctelegram && composer.phar update
``` 
5. Clean cache. Just click clean cache in Live Helper Chat back office.
6. Execute doc/install.sql on database manager or just run. You will have to wait 10 seconds for queries to be executed.
    ```
    php cron.php -s site_admin -e lhctelegram -c cron/update_structure
