### ISSUE TITLE
[Feature] Support telegram group chats

### ISSUE THREAD

**Issue by gituser** [LiveHelperChat/telegram#42]
Hi @remdex 

Would be nice to be able to support group chats.

Why it's nice?  - When you have multiple support agents and some of them are online or not they could reply directly in the group chat to the bot and give the user instant reply in the chat.

What basically needs to be done:
* set-up a bot as usual
* add the bot into the new telegram group
* get group id (usually a negative id like -43434343434 something), you can get this group id by multiple methods, e.g. via [getUpdates](https://core.telegram.org/bots/api#getupdates) call 
* specify group id inside the settings of the bot
* when someone quotes the bot message and gives a reply, reply goes to the user 

What do you think?

Thanks!

**Comment by remdex** [comment]
Sounds good. Please develop it I'll accept pull request.

**Comment by gituser** [comment]
@remdex by looking at the issue, this feature request already has been submitted in https://github.com/LiveHelperChat/telegram/issues/30

I'm not familiar with the LHC code or Telegram plugin for it. 

Btw, is it possible to adopt telegram plugin as a laravel module if LHC is installed in laravel mode?

Do you have any dev guidelines from where to start?

Thanks.

**Comment by remdex** [comment]
Well it should work and should not matter how lhc is installed :) if it does not just debug and fix it :)

**Comment by remdex** [comment]
It was implemented. Please see new instructions

**Comment by mafaza86** [comment]
> instructions

Sorry, how to implement it? My Telegram client integration is already running.

I have added the Telegram bot to the group, and have tried tagging the bot, but it still doesn't enter the live chat queue.

Please help, thanks.

**Comment by remdex** [comment]
Update lhc, update telegram extension including composer dependencies.

Read new instructions... you can try out on my hosting for demo :)
