### ISSUE TITLE
Unable to reply chat from telegram

### ISSUE THREAD

**Issue by tonygeorge0707** [LiveHelperChat/telegram#59]
Hi,

I have followed the steps on https://www.youtube.com/watch?v=wObbEaeopRU . I am not getting the telegram chat ID or group ID when clicking on set webhook on Telegram settings - Operators. The chats are reaching the telegram bot normally but I am unable to reply through Telegram. Attaching the recent audit log for reference.

[400]Bad Request: the chat is not a forum-#0 /var/www/clients/client1/web1/web/livehelp/lib/core/lhchat/lhchateventdispatcher.php(70): erLhcoreClassExtensionLhctelegram->chatStarted()
#1 /var/www/clients/client1/web1/web/livehelp/cache/compiledtemplates/9da08037756b087e04d803bee2783869.php(11): erLhcoreClassChatEventDispatcher->dispatch()
#2 /var/www/clients/client1/web1/web/livehelp/lib/core/lhcore/lhmodule.php(108): include('...')
#3 /var/www/clients/client1/web1/web/livehelp/lib/core/lhcore/lhmodule.php(658): erLhcoreClassModule::runModule()
#4 /var/www/clients/client1/web1/web/livehelp/index.php(53): erLhcoreClassModule::moduleInit()
#5 {main}

**Comment by remdex** [comment]
It's just something you did not do... Nothing I can help with that... It comes form telegram. Means you missing on telegram setup...
