### ISSUE TITLE
composer.phar: command not found

### ISSUE THREAD

**Issue by s2353553** [LiveHelperChat/telegram#61]
Hi, Thanks for all your efforts but unfortunately the same as this post https://forum.livehelperchat.com/viewtopic.php?id=3253 I can't get any further with step 4. If I enter this here, I get a message every time that the command cannot be found:
cd extension/lhctelegram && composer.phar update

The message is:
composer.phar: command not found

Spending lots of time but cant get further, any help would be much appreciated!

**Comment by remdex** [comment]
just google what composer is and how to install it
