### ISSUE TITLE
Truble with add operator to group 

### ISSUE THREAD

**Issue by ozadorozhnykh** [LiveHelperChat/telegram#62]
Greetings!
I had a problem with adding an operator to a Telegram group using a bot.
Today I cloned the repository, added the module according to the instructions, added the bot to the module settings,

![2024-09-28_23-02](https://github.com/user-attachments/assets/8bf9059e-135d-4487-a02a-486b3b326fc0)
created a new operator telegram
![image](https://github.com/user-attachments/assets/cd2b05f1-0565-44c9-92e6-e8a570b8dc0d)
register it in bot 
![image](https://github.com/user-attachments/assets/89eab2e7-537c-4d28-b0b8-5ea565ee5a5a)
add Group chat id in settings
![image](https://github.com/user-attachments/assets/a521dc95-abe0-4c81-b3bc-c1a77ef79a02)
make bot how admin group 

I tried how in video register operator in group chat  but, i receive message 
"Operator is already confirmed! Please un-confirm operator first in back office"

Ok, i tried  un-confirm operator 
![image](https://github.com/user-attachments/assets/dada22db-7956-4828-b682-41c8e1eb976b)
and after send 
"/register 7"
and not reaction.
Please help me, I don't understand what I'm doing wrong and where could be the mistake

**Comment by remdex** [comment]
You should not have clicked confirmed manually. It will confirm automatically once you issue command /register id

**Comment by ozadorozhnykh** [comment]
ok, but how can i register operator in group chat? Maybe just add in mysql &

**Comment by remdex** [comment]
Each operator has to issue register command within a bot. You can't do for other ops it.
