### ISSUE TITLE
error on new bot

### ISSUE THREAD

**Issue by MrDevIr** [LiveHelperChat/telegram#7]
Hi, thanks for adding telegram bot extension. I get this error on saving new telegram bot.

> Could not fetch the persistent object definition for the class 'erLhcoreClassModelTelegramBot'. Searched for '/erlhcoreclassmodeltelegrambot.php'

I'm not familiar with php.
php ver 7.1.0

**Comment by remdex** [comment]
Sorry, but i cannot reproduce :) What path you are entering in your browser. And have you installed dependencies using composer?

**Comment by MrDevIr** [comment]
I have reinstalled LHC the problem is solved. Think something caused that problem after updating LHC. 
Now I have ssl problem.

> SSL certificate problem: self signed certificate in certificate chain.
