### ISSUE TITLE
Telegram returned an invalid response! Please review your bot name and API key.

### ISSUE THREAD

**Issue by shionphan** [LiveHelperChat/telegram#8]
Hi

It report error message that is 'Telegram returned an invalid response! Please review your bot name and API key.' when I click the webhook button.  But I'm pretty sure my token is correct which show in follow screenshot.

https://api.telegram.org/bot123456:xxxx/getMe

![image](https://user-images.githubusercontent.com/12638956/38465427-181449f8-3b4e-11e8-87b9-23496d3b9efd.png)

**Comment by remdex** [comment]
Hi,
You get this error. Then try to send message back to visitor? Do you receive messages from telegram bot to LHC?

**Comment by shionphan** [comment]
@remdex  Just stop at  step 11 which from https://livehelperchat.com/how-to-use-telegram-if-you-are-automated-hosting-client-489a.html. Then it report the error message.

![image](https://user-images.githubusercontent.com/12638956/38468279-27f4bc90-3b76-11e8-845f-f7f91fce49b8.png)
