### ISSUE TITLE
Operator Selection Improvements

### ISSUE THREAD

**Issue by dkwiebe** [LiveHelperChat/telegram#9]
Please put these on my bill.

In the "Edit Operator" page we'd like to have it show both first name and last name.   Right now the Operator dropdown only shows the operators first name.  As the number of operators in the system climbs they get harder to find.

![image](https://user-images.githubusercontent.com/1034679/41866387-34371050-786d-11e8-9222-2de27911641f.png)

**Comment by remdex** [comment]
Implemented
